version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.8 #installing python version 3.8
  pre_build:
    on-failure: CONTINUE
    commands:
      - echo ****Checking if python installed successfully****
      - python3 --version #will return the version of python that has been installed
      - echo ***Checking if pip3 is installed***
      - pip3 --version
      - echo ***installing cfn-lint***
      - pip3 install cfn-lint
      - echo ***checking if cfn-lint is installed***
      - cfn-lint --version
  build:
    on-failure: ABORT
    commands:
      - echo ***Build started at `date` ***
      - pwd
      - cfn-lint launch_instance_in_custom_vpc.yml
      - echo ***Building the cloudformation template***
      - aws cloudformation package --template-file launch_instance_in_custom_vpc.yml --s3-bucket deployed-cloudformation-artifacts-bucket --output-template-file OutputTemplate.yml
  post_build:
    on-failure: ABORT
    commands:
      - echo ***Build complete***
      - ls -l
artifacts:
  files:
    - OutputTemplate.yml